image: python:latest

requirements:
    stage: build
    script:
        pip install -r requirements.txt



pytest:
    stage: test
    script:
        export PYTHONPATH="$PYTHONPATH:."
        python -c "import sys;print(sys.path)"
        pytest -v
